# Generated by Django 5.2.14 on 2026-06-03 07:50

import builtins
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効・無効')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='従業員番号')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='ミドルネーム')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('noanswer', '回答無し')], max_length=10, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='誕生日')),
                ('tel', models.CharField(max_length=11, verbose_name='電話番号')),
                ('postcode', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=5, verbose_name='都道府県')),
                ('city', models.CharField(max_length=10, verbose_name='市町村')),
                ('address1', models.CharField(max_length=50, verbose_name='番地以降')),
                ('address2', models.CharField(max_length=50, verbose_name='マンション名など')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='日報')),
                ('content', models.TextField(verbose_name='日報内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('approved', '承認済み'), ('return', '差し戻し')], verbose_name='ステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailyreports', to=settings.AUTH_USER_MODEL, verbose_name='日報')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='部署名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効・無効')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_reports.departments', verbose_name='親部門コード')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='daily_reports.departments', verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily_reports.roles', verbose_name='権限'),
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, verbose_name='テンプレート名')),
                ('content_layout', models.TextField(blank=True, max_length=builtins.max, null=True, verbose_name='テンプレート内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効・無効')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_reports.departments', verbose_name='部署ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='週報タイトル')),
                ('content', models.TextField(verbose_name='週報内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('approved', '承認済み'), ('return', '差し戻し')], verbose_name='ステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeklyreports', to=settings.AUTH_USER_MODEL, verbose_name='日報')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags', to='daily_reports.dailyreports')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags', to='daily_reports.tag')),
            ],
            options={
                'db_table': 'report_tags',
                'constraints': [models.UniqueConstraint(fields=('report', 'tag'), name='unique_report_tag')],
            },
        ),
    ]
