# Generated by Django 5.2.14 on 2026-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='マンション名など'),
        ),
    ]
